RecipeRush/recipes/urls.py
from django.conf.urls.static import static
from django.urls import path

from .views import RecipeCreateView, RecipeDetailsView, RecipeEditView, RecipeDeleteView, Index, UserRecipesDetailsView, \
    like_recipe, BrowseByCategoryView, LikedRecipesView, CommentDeleteView, RecipeSearchView

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('create-recipe/', RecipeCreateView.as_view(), name='recipe-create'),
    path('details-recipe/<int:pk>', RecipeDetailsView.as_view(), name='recipe-details'),
    path('edit-recipe/<int:pk>', RecipeEditView.as_view(), name='recipe-edit'),
    path('delete-recipe/<int:pk>', RecipeDeleteView.as_view(), name='recipe-delete'),
    path('user-recipes/<int:pk>', UserRecipesDetailsView.as_view(), name='user-recipes'),
    path('recipe/like/<int:pk>/', like_recipe, name='recipe-like'),
    path('browse-recipes/<str:category>', BrowseByCategoryView.as_view(), name='browse-recipes'),
    path('liked-recipes/', LikedRecipesView.as_view(), name='liked-recipes'),
    path('comment-delete/<int:pk>', CommentDeleteView.as_view(), name='comment-delete'),
    path('search/', RecipeSearchView.as_view(), name='recipe-search'),
]

RecipeRush/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from RecipeRush import settings
from django.conf.urls import handler404

from RecipeRush.recipes.views import custom_404

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('RecipeRush.recipes.urls')),
                  path('account/', include('RecipeRush.accounts.urls'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = custom_404

RecipeRush/recipes/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator
from django.db import models
from django.utils import timezone

UserModel = get_user_model()


class Recipe(models.Model):
    CHOICES = [
        ('main-dish', "Main Dish"),
        ('side-dish', "Side Dish"),
        ('starter', 'Starter'),
        ("salad", "Salad"),
        ('soup', 'Soup'),
        ('dessert', 'Dessert')
    ]
    title = models.CharField(null=False, blank=False, max_length=40, validators=[MinLengthValidator(3)])
    description = models.CharField(null=False, blank=False, max_length=200, validators=[MinLengthValidator(5)])
    ingredients = models.TextField(null=False, blank=False, max_length=400, validators=[MinLengthValidator(5)])
    instructions = models.TextField(null=False, blank=False, max_length=2500)
    category = models.CharField(null=False, blank=False, max_length=9, choices=CHOICES)
    author = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='recipes')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    picture = models.ImageField(upload_to='recipe_pics/', null=False, blank=False)

    def __str__(self):
        return self.title


class Likes(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'recipe')


class Comment(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='comments')
    commenter_name = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    comment_text = models.TextField()
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.commenter_name} on {self.recipe.title} - {self.timestamp}"

    def save(self, *args, **kwargs):
        if not self.id:  # Only set the commenter on object creation, not on update
            user = kwargs.pop('user', None)
            if user:
                self.commenter = user
        super().save(*args, **kwargs)

RecipeRush/recipes/forms.py
from django import forms
from .models import Recipe, Comment


class RecipeCreateForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-user', 'placeholder': 'Recipe Title'}),
        required=True)
    description = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-user', 'placeholder': 'Description'}),
        required=True)
    ingredients = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control form-control-user',
                                     'placeholder': 'Ingredients', 'style': 'height: 80px'}),
        required=True)
    instructions = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control form-control-user',
                                     'placeholder': 'Instructions', 'style': 'height: 80px'}),
        required=True)
    category = forms.TypedChoiceField(
        choices=Recipe.CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'}),
        coerce=str,
        required=True)

    picture = forms.ImageField(label='Recipe Picture:')

    class Meta:
        model = Recipe
        fields = ('title', 'ingredients', 'instructions', 'category', 'picture', 'description')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['picture'].widget.attrs.update({'enctype': 'multipart/form-data'})


class RecipeEditForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-user', 'placeholder': 'Recipe Title'}),
        required=True)
    description = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-user', 'placeholder': 'Description'}),
        required=True)
    ingredients = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control form-control-user',
                                     'placeholder': 'Ingredients', 'style': 'height: 80px'}),
        required=True)
    instructions = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control form-control-user',
                                     'placeholder': 'Instructions', 'style': 'height: 80px'}),
        required=True)
    category = forms.TypedChoiceField(
        choices=Recipe.CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'}),
        coerce=str,
        required=True)

    picture = forms.ImageField(label='Recipe Picture:')

    class Meta:
        model = Recipe
        fields = ('title', 'description', 'ingredients', 'instructions', 'category', 'picture',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['picture'].widget.attrs.update({'enctype': 'multipart/form-data'})


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text']
        widgets = {
            'comment_text': forms.Textarea(
                attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Write your comment here...'}, ),
        }

RecipeRush/recipes/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic as generic_views
from rest_framework import filters, generics

from RecipeRush.recipes.forms import RecipeCreateForm, RecipeEditForm, CommentForm
from RecipeRush.recipes.models import Recipe, Likes, Comment
from RecipeRush.recipes.serializers import RecipeSerializer

required_login = method_decorator(login_required, name='dispatch')
UserModel = get_user_model()


# Create your views here.
class Index(generic_views.ListView):
    template_name = 'common/index.html'
    context_object_name = 'top_liked_recipes'

    def get_queryset(self):
        # Get the top 3 most liked recipes
        return Recipe.objects.annotate(num_likes=Count('likes__recipe')).order_by('-num_likes')[:3]


@required_login
class RecipeCreateView(generic_views.CreateView):
    template_name = 'recipes/recipe-create.html'
    model = Recipe
    form_class = RecipeCreateForm

    def get_success_url(self):
        return reverse_lazy('user-recipes', kwargs={'pk': self.request.user.pk})

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeDetailsView(generic_views.DetailView):
    template_name = 'recipes/recipe-details.html'
    model = Recipe
    context_object_name = 'recipe'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        return context

    def post(self, request, pk):
        recipe = get_object_or_404(Recipe, pk=pk)
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comment_text = comment_form.cleaned_data['comment_text']
            commenter_name = request.user  # Assuming the user is logged in
            comment = Comment.objects.create(recipe=recipe, commenter_name=commenter_name, comment_text=comment_text)
            # You can also set the timestamp field here if needed

        # Refresh the recipe object from the database to include the new comment
        recipe.refresh_from_db()

        context = {
            'recipe': recipe,
            'comment_form': comment_form,
        }

        return render(request, 'recipes/recipe-details.html', context)


@required_login
class UserRecipesDetailsView(generic_views.ListView):
    model = Recipe
    template_name = 'recipes/user-recipes.html'
    context_object_name = 'user_recipes'

    def get_queryset(self):
        user_pk = self.kwargs.get('pk')
        user = get_object_or_404(UserModel, pk=user_pk)
        return Recipe.objects.filter(author=user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_pk = self.kwargs.get('pk')
        user = get_object_or_404(UserModel, pk=user_pk)
        context['author_name'] = user.username
        return context


@required_login
class RecipeDeleteView(generic_views.DeleteView):
    model = Recipe
    template_name = 'recipes/recipe-delete.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Recipe, pk=self.kwargs['pk'])

    def get_success_url(self):
        return reverse_lazy('user-recipes', kwargs={'pk': self.request.user.pk})


@required_login
class RecipeEditView(generic_views.UpdateView):
    model = Recipe
    template_name = 'recipes/recipe-edit.html'
    form_class = RecipeEditForm

    def get_success_url(self):
        return reverse_lazy('recipe-details', kwargs={'pk': self.kwargs['pk']})


@login_required
def like_recipe(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk)
    if Likes.objects.filter(user=request.user, recipe=recipe).exists():
        Likes.objects.filter(user=request.user, recipe=recipe).delete()
    else:
        Likes.objects.create(user=request.user, recipe=recipe)

    # Redirect back to the recipe detail page after liking/unliking
    return redirect('recipe-details', pk=pk)


class BrowseByCategoryView(generic_views.ListView):
    model = Recipe
    template_name = 'recipes/browse-recipes.html'
    context_object_name = 'recipes'

    def get_queryset(self):
        category = self.kwargs['category']
        return Recipe.objects.filter(category=category)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = self.kwargs.get('category')
        context['category'] = category  # Add the category to the context
        return context


@required_login
class LikedRecipesView(generic_views.ListView):
    template_name = 'recipes/recipe-liked.html'
    context_object_name = 'liked_recipes'

    def get_queryset(self):
        user = self.request.user
        return Recipe.objects.filter(likes__user=user)


def custom_404(request, exception):
    return render(request, 'common/404.html', status=404)


@required_login
class CommentDeleteView(generic_views.View):
    def get(self, request, pk):
        comment = get_object_or_404(Comment, pk=pk)
        comment.delete()
        return redirect('recipe-details', pk=comment.recipe.pk)


class RecipeSearchView(generics.ListAPIView):   # Using Django REST framework
    queryset = Recipe.objects.all()
    serializer_class = RecipeSerializer
    filter_backends = [filters.SearchFilter]
    search_fields = ['title', 'ingredients', 'category']

    def get_queryset(self):
        queryset = super().get_queryset()
        search_input = self.request.query_params.get('q')
        if search_input:
            queryset = queryset.filter(title__icontains=search_input) | \
                       queryset.filter(ingredients__icontains=search_input) | \
                       queryset.filter(category__icontains=search_input)
        else:
            queryset = queryset.none()
        return queryset

    def list(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        context = {'object_list': queryset, 'search_input': request.query_params.get('q')}
        return render(request, 'recipes/search_results.html', context)

templates/recipes/browse-recipes.html
{% extends 'base/base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
    <div class="container">
        <h2 class="mb-4 mt-3">Selected Category: {{ category|replace }}</h2>
        <div class="row">
            {% for recipe in recipes %}
                <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
                    <div class="card position-relative h-100">
                        <img class="card-img-top img-fluid" src="{{ recipe.picture.url }}" alt="Card image cap">
                        <div class="card-body d-flex flex-column">
                            <h5 class="card-title text-dark font-weight-bold">{{ recipe.title }}</h5>
                            <p class="card-text flex-grow-1">{{ recipe.description|truncatechars:100 }}</p>
                            <div class="mt-auto">
                                <a href="{% url 'recipe-details' pk=recipe.pk %}"
                                   class="btn btn-primary btn-sm d-block mx-auto">View Recipe</a>
                            </div>
                        </div>
                        <div class="card-footer d-flex justify-content-between">
                            <small class="text-muted">Last Updated: {{ recipe.updated_at }}</small>
                            <small class="text-muted">
                                {% if request.user.is_authenticated %}
                                    {% if recipe|has_liked:request.user %}
                                        <i class="fas fa-heart heart-full text-danger"></i>
                                    {% else %}
                                        <i class="far fa-heart heart-gray"></i>
                                    {% endif %}
                                {% else %}
                                    <i class="far fa-heart heart-gray"></i>
                                {% endif %}
                                <span class="likes-count">{{ recipe.likes_set.count }}</span>
                            </small>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/recipes/recipe-details.html
{% extends 'base/base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
    <style>
        .text-wrap {
            white-space: pre-wrap;
            max-width: 100%;
            overflow-wrap: break-word;
        }
    </style>
    <div class="d-flex">
        <div class="container mt-5 ml-5">
            <div class="row justify-content-around">
                <div class="col-md-8">
                    <h1 class="display-4 text-uppercase font-weight-bolder text-primary text-wrap">{{ recipe.title }}</h1>
                    <h2 class="text-dark text-wrap">{{ recipe.description }}</h2>
                    <img src="{{ recipe.picture.url }}" alt="{{ recipe.title }}" class="img-fluid mb-3"
                         style="width: 450px; height: 350px; object-fit: cover">

                    <h2 class="font-weight-bold text-primary">Ingredients</h2>
                    <p class="text-dark h5 text-wrap">{{ recipe.ingredients|linebreaksbr }}</p>

                    <h2 class="font-weight-bold text-primary ">Instructions</h2>
                    <p class="text-dark h5 mb-5 text-wrap">{{ recipe.instructions|linebreaksbr }}</p>

                    <p class="text-dark mt-5 mb-0">Created At: {{ recipe.created_at }}</p>
                    <p class="text-dark">Updated At: {{ recipe.updated_at }}</p>
                </div>
                <div class="col-md-4">
                    <div class="container mt-3 mt-md-0 m-5">
                        <p class="text-dark h2 mb-5"><span
                                class="text-primary">Category:</span> <a class="badge badge-light"
                                                                         href="{% url 'browse-recipes' category=recipe.category %}">{{ recipe.get_category_display }}</a>
                        </p>
                        <p class="text-dark h2 mb-5"><span
                                class="text-primary">Author:</span> <a class="badge badge-light"
                                                                       href="{% url 'account-details' pk=recipe.author.pk %}">{{ recipe.author }}</a>
                        </p>
                        <p class="text-dark h2 mb-5">
                            {% if request.user.is_authenticated %}
                                {% if recipe|has_liked:request.user %}
                                    <a href="{% url 'recipe-like' pk=recipe.pk %}" class="like-btn text-danger"
                                       style="cursor: pointer">
                                        <i class="fas fa-heart heart-full"></i></a>
                                {% else %}
                                    <a href="{% url 'recipe-like' pk=recipe.pk %}" class="like-btn text-secondary"
                                       style="cursor: pointer">
                                        <i class="far fa-heart heart-empty"></i></a>
                                {% endif %}
                            {% else %}
                                <a href="{% url 'account-login' %}" class="text-secondary">
                                    <i class="far fa-heart heart-empty"></i></a>
                            {% endif %}
                            <span class="likes-count">{{ recipe.likes_set.count }}</span></p>
                        {% if request.user.pk == recipe.author.pk %}
                            <a href="{% url 'recipe-edit' pk=recipe.pk %}" class="btn btn-primary">Edit
                                Recipe</a>

                            <a href="{% url 'recipe-delete' pk=recipe.pk %}" class="btn btn-danger">Delete
                                Recipe</a>
                        {% endif %}

                        <div class="mt-5">
                            <h3 class="mb-3 text-primary font-weight-bold">Add a Comment</h3>
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    {{ comment_form.comment_text }}
                                </div>
                                {% if request.user.is_authenticated %}
                                    <button type="submit" class="btn btn-primary">Post Comment</button>
                                {% else %}
                                    <a href="{% url 'account-login' %}" class="btn btn-primary">Post Comment</a>
                                {% endif %}
                            </form>
                        </div>
                        <hr>
                        <!-- Display Existing Comments -->
                        <h3 class="mt-4 text-primary font-weight-bold">Comments</h3>
                        <div class="d-flex flex-column">
                            {% for comment in recipe.comments.all %}
                                <div class="card-body d-flex justify-content-between">
                                    <div>
                                        <h5 class="card-title text-primary">{{ comment.commenter_name }}</h5>
                                        <p class="card-text">{{ comment.comment_text }}</p>
                                        <p class="card-text"><small class="text-muted">{{ comment.timestamp }}</small>
                                        </p>
                                    </div>
                                    {% if request.user.pk == comment.commenter_name.pk or request.user.pk == recipe.author.pk %}
                                        <a href="{% url 'comment-delete' comment.pk %}"
                                           class="btn btn-sm btn-danger h-100">
                                            <i class="fas fa-trash-alt"></i>
                                        </a>
                                    {% endif %}
                                </div>
                                <hr class="mb-0">
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/recipes/recipe-liked.html
{% extends 'base/base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
    {% if not liked_recipes %}
        <div class="d-flex justify-content-center h-75">
            <div class="d-flex justify-content-center flex-column align-items-center">
                <p class="font-weight-bolder display-4">You haven't liked any recipes yet. <i
                        class="fas fa-sad-tear"></i>
                </p>
            </div>
        </div>
    {% else %}
        <div class="container">
            <h2 class="mb-4">Liked Recipes</h2>
            <div class="row">
                {% for recipe in liked_recipes %}
                    <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
                        <div class="card position-relative h-100">
                            <img class="card-img-top img-fluid" src="{{ recipe.picture.url }}" alt="Card image cap">
                            <div class="card-body d-flex flex-column">
                                <h5 class="card-title text-dark font-weight-bold">{{ recipe.title }}</h5>
                                <p class="card-text flex-grow-1">{{ recipe.description|truncatechars:100 }}</p>
                                <div class="mt-auto">
                                    <a href="{% url 'recipe-details' pk=recipe.pk %}"
                                       class="btn btn-primary btn-sm d-block mx-auto">View Recipe</a>
                                </div>
                            </div>
                            <div class="card-footer d-flex justify-content-between">
                                <small class="text-muted">Last Updated: {{ recipe.updated_at }}</small>
                                <small class="text-muted">
                                    {% if request.user.is_authenticated %}
                                        {% if recipe|has_liked:request.user %}
                                            <i class="fas fa-heart heart-full text-danger"></i>
                                        {% else %}
                                            <i class="far fa-heart heart-gray"></i>
                                        {% endif %}
                                    {% else %}
                                        <i class="far fa-heart heart-gray"></i>
                                    {% endif %}
                                    <span class="likes-count">{{ recipe.likes_set.count }}</span>
                                </small>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/recipes/search_results.html
{% extends 'base/base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
    {% if not object_list %}
        <div class="d-flex justify-content-center h-75">
            <div class="d-flex justify-content-center flex-column align-items-center">
                <p class="font-weight-bolder display-4">No results matching your search '{{ search_input }}'.</p>
            </div>
        </div>
    {% else %}
        <div class="container">
            <h2 class="mb-4">Results for your search '{{ search_input }}'</h2>
            <div class="row">
                {% for recipe in object_list %}
                    <div class="col-sm-4 mb-4">
                        <div class="card">
                            <img class="card-img-top img-fluid" src="{{ recipe.picture.url }}" alt="Card image cap">
                            <div class="card-body">
                                <h5 class="card-title text-dark font-weight-bold">{{ recipe.title }}</h5>
                                <p class="card-text">{{ recipe.description }}</p>
                                <div class="d-flex justify-content-center">
                                    <a href="{% url 'recipe-details' pk=recipe.pk %}"
                                       class="btn btn-primary btn-sm">View Recipe</a>
                                </div>

                            </div>
                            <div class="card-footer d-flex justify-content-between">
                                <small class="text-muted">Last Updated: {{ recipe.updated_at }}</small>
                                <small class="text-muted">
                                    {% if request.user.is_authenticated %}
                                        {% if recipe|has_liked:request.user %}
                                            <i class="fas fa-heart heart-full text-danger"></i>
                                            <!-- Full red heart icon if user has liked -->
                                        {% else %}
                                            <i class="far fa-heart heart-gray"></i>
                                            <!-- Gray heart icon if user has not liked -->
                                        {% endif %}
                                    {% else %}
                                        <i class="far fa-heart heart-gray"></i>
                                        <!-- Gray heart icon for unauthenticated users -->
                                    {% endif %}
                                    <span class="likes-count">{{ recipe.likes_set.count }}</span>
                                </small>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/recipes/user-recipes.html
{% extends 'base/base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
    {% if not user_recipes %}
        <div class="d-flex justify-content-center h-75">
            <div class="d-flex justify-content-center flex-column align-items-center">
                <p class="font-weight-bolder display-4">User doesn't have any recipes yet. <i
                        class="fas fa-sad-tear"></i>
                </p>
            </div>
        </div>
    {% else %}
        <div class="container">
            <h2 class="mb-4">{{ author_name }}'s Recipes</h2>
            <div class="row">
                {% for recipe in user_recipes %}
                    <div class="col-sm-4 mb-4">
                        <div class="card position-relative">
                            <img class="card-img-top img-fluid" src="{{ recipe.picture.url }}" alt="Card image cap">
                            <div class="card-body">
                                <h5 class="card-title text-dark font-weight-bold center">{{ recipe.title }}</h5>
                                <p class="card-text ">{{ recipe.description }}</p>
                            </div>
                            <div class="position-absolute bottom-center w-100" style="top: 456px; left: 120px">
                                <a href="{% url 'recipe-details' pk=recipe.pk %}"
                                   class="btn btn-primary btn-sm ">View Recipe</a>
                            </div>
                            <div class="card-footer d-flex justify-content-between">
                                <small class="text-muted">Last Updated: {{ recipe.updated_at }}</small>
                                <small class="text-muted">
                                    {% if request.user.is_authenticated %}
                                        {% if recipe|has_liked:request.user %}
                                            <i class="fas fa-heart heart-full text-danger"></i>
                                            <!-- Full red heart icon if user has liked -->
                                        {% else %}
                                            <i class="far fa-heart heart-gray"></i>
                                            <!-- Gray heart icon if user has not liked -->
                                        {% endif %}
                                    {% else %}
                                        <i class="far fa-heart heart-gray"></i>
                                        <!-- Gray heart icon for unauthenticated users -->
                                    {% endif %}
                                    <span class="likes-count">{{ recipe.likes_set.count }}</span>
                                </small>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock %}